{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  noarch: python
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
  - "{{ PYTHON }} -m pip install {{ SRC_DIR }} -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob
    - bob.io.base
    - bob.bio.base
    - clapper {{ clapper }}
    - docopt {{ docopt }}
    - matplotlib {{ matplotlib }}
    - numpy {{ numpy }}
    - pillow {{ pillow }}
    - schema {{ schema }}
    - scikit-image {{ scikit_image }}
    - scipy {{ scipy }}

  run:
    - python
    - setuptools
    - bob
    - bob.io.base
    - bob.bio.base
    - {{ pin_compatible('clapper') }}
    - {{ pin_compatible('docopt') }}
    - {{ pin_compatible('matplotlib') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pillow') }}
    - {{ pin_compatible('schema') }}
    - {{ pin_compatible('scikit-image') }}
    - {{ pin_compatible('scipy') }}

test:
  imports:
    - {{ name.replace('-','_') }}
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}

about:
  home: {{ data['project']['urls']['homepage'] }}
  summary: {{ data['project']['description'] }}
  license: {{ data['project']['license']['text'] }}
  license_family: GPL
